### ISSUE TITLE
Predefined value cannot be deleted

### ISSUE THREAD

**Issue by coax** [Mavrin/maskInput#14]
Version 1.1.1: if you have multiple input "text" fields (with populated values), the last input field disables delete or backspace keystroke.

eg:
```
<script>
$('.int').numberMask();
</script>

<input type="text" value="1" class="int">
<input type="text" value="2" class="int">
<input type="text" value="3" class="int">
<input type="text" value="4" class="int">
```
In example above 4 cannot be deleted.

**Comment by Mavrin** [comment]
I can reproduce you case. Which a browser do you use?

**Comment by coax** [comment]
Tested in all major browsers (latest). If you cannot reproduce it - it must be on my end (even though I tested for that). Nevermind, you can close the issue as I've moved to another plugin. Thanks.
