### ISSUE TITLE
Thousand separator

### ISSUE THREAD

**Issue by tng10** [Mavrin/maskInput#9]
Hello,

I would like to ask if is possible to use thousand separator in this plugin.

Thank You.

**Comment by Mavrin** [comment]
Hello, 
What do you mean `thousand separator`?

**Comment by tng10** [comment]
Let's suppose you have the following number <b>1234567,89</b> (without thousand separators) and now with thousand separators (<b>1.234.567,89</b>). 

Do you think is possible to accept this dots in your plugin?

**Comment by Mavrin** [comment]
You can try `$('.mask').numberMask({pattern:/^\d*[\.{0,1}|\d*|,{0,1}]*\d*$/});` http://jsfiddle.net/taucharts/VRyML/1/ . But i don't sure that will be suitable for you.

**Comment by tng10** [comment]
@Mavrin I decided to use a number without thousand separators, so I did a workaround before the usage of your plugin. Thank you very much for your answer.
